# Generated by Django 4.0.2 on 2022-03-11 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_endorsement_question_skill_logo_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
